# Telangana Vehicle Sales 2023 🚗

#### Kaggle link for dataset -- https://www.kaggle.com/datasets/zubairatha/revving-up-telangana-vehicle-sales-2023

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv('D:\\Data Science\\Datasets\\For_statistics\\03_Telangana_vehicles\\telangana_vehicle_sales.csv')
df.head(2)

slno             modelDesc    fuel                colour vehicleClass  \
0  19139  ACTIVA - 6G DLX BSVI  PETROL  DECENT BLUE METALLIC  MOTOR CYCLE   
1  19210  ACTIVA - 6G DLX BSVI  PETROL  DECENT BLUE METALLIC  MOTOR CYCLE   

     makeYear  seatCapacity insuranceValidity secondVehicle  \
0  01/08/2022             2        01/01/2028             Y   
1  01/09/2022             2        01/01/2028             Y   

  tempRegistrationNumber       category                       makerName  \
0           TS11AGTR3069  Non Transport  HONDA MOTORCYCLE&SCOOTER(I)P L   
1           TS11AGTR3340  Non Transport  HONDA MOTORCYCLE&SCOOTER(I)P L   

      OfficeCd    fromdate      todate  
0  RTA MEDCHAL  01/01/2023  02/01/2023  
1  RTA MEDCHAL  01/01/2023  02/01/2023

In [3]:
df.shape

(627866, 15)

In [5]:
## Setting option to view the maximum number of columns
pd.set_option('display.max_columns',15)

In [6]:
df.head()

slno             modelDesc    fuel                colour vehicleClass  \
0  19139  ACTIVA - 6G DLX BSVI  PETROL  DECENT BLUE METALLIC  MOTOR CYCLE   
1  19210  ACTIVA - 6G DLX BSVI  PETROL  DECENT BLUE METALLIC  MOTOR CYCLE   
2  19308  ACTIVA - 6G DLX BSVI  PETROL  DECENT BLUE METALLIC  MOTOR CYCLE   
3  19309  ACTIVA - 6G DLX BSVI  PETROL  DECENT BLUE METALLIC  MOTOR CYCLE   
4  19329  ACTIVA - 6G DLX BSVI  PETROL  DECENT BLUE METALLIC  MOTOR CYCLE   

     makeYear  seatCapacity insuranceValidity secondVehicle  \
0  01/08/2022             2        01/01/2028             Y   
1  01/09/2022             2        01/01/2028             Y   
2  01/10/2022             2        01/01/2028             N   
3  01/10/2022             2        01/01/2028             N   
4  01/11/2022             2        01/01/2028             N   

  tempRegistrationNumber       category                       makerName  \
0           TS11AGTR3069  Non Transport  HONDA MOTORCYCLE&SCOOTER(I)P L   
1           TS11AGTR3340  Non Transport  HONDA MOTORCYCLE&SCOOTER(I)P L   
2           TS11AGTR3027  Non Transport  HONDA MOTORCYCLE&SCOOTER(I)P L   
3           TS11AGTR3072  Non Transport  HONDA MOTORCYCLE&SCOOTER(I)P L   
4           TS11AGTR4864  Non Transport  HONDA MOTORCYCLE&SCOOTER(I)P L   

           OfficeCd    fromdate      todate  
0       RTA MEDCHAL  01/01/2023  02/01/2023  
1       RTA MEDCHAL  01/01/2023  02/01/2023  
2       RTA MEDCHAL  01/01/2023  02/01/2023  
3       RTA MEDCHAL  01/01/2023  02/01/2023  
4  RTA-HYDERABAD-CZ  01/01/2023  02/01/2023

In [7]:
# Checking the null values for the DF

pd.isnull(df).sum()

slno                          0
modelDesc                     0
fuel                      12851
colour                      319
vehicleClass                  0
makeYear                      0
seatCapacity                  0
insuranceValidity           135
secondVehicle                 0
tempRegistrationNumber        0
category                      0
makerName                     0
OfficeCd                      0
fromdate                      0
todate                        0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 627866 entries, 0 to 627865
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype 
---  ------                  --------------   ----- 
 0   slno                    627866 non-null  int64 
 1   modelDesc               627866 non-null  object
 2   fuel                    615015 non-null  object
 3   colour                  627547 non-null  object
 4   vehicleClass            627866 non-null  object
 5   makeYear                627866 non-null  object
 6   seatCapacity            627866 non-null  int64 
 7   insuranceValidity       627731 non-null  object
 8   secondVehicle           627866 non-null  object
 9   tempRegistrationNumber  627866 non-null  object
 10  category                627866 non-null  object
 11  makerName               627866 non-null  object
 12  OfficeCd                627866 non-null  object
 13  fromdate                627866 non-null  object
 14  todate                  627866 non-n

In [9]:
# Checking the unique value in the "fuel" column

df['fuel'].unique()

# Found the value of nan and -1

array(['PETROL', 'BATTERY', 'CNG PETROL', 'DIESEL', nan, 'PETROL LPG',
       '-1', 'CNG', 'PETROL CNG', 'PETROL ELECTRIC', 'LPG'], dtype=object)

In [10]:
# Checking the values for fuel

df['fuel'].value_counts()

fuel
PETROL             477920
DIESEL              78600
BATTERY             36508
CNG PETROL          15571
PETROL LPG           3951
CNG                  2117
-1                    197
PETROL ELECTRIC        87
PETROL CNG             51
LPG                    13
Name: count, dtype: int64

In [11]:
#Checking the values for vehicleClass

df['vehicleClass'].unique()

array(['MOTOR CYCLE', 'MOTOR CAR', 'Motor Cab',
       'Three Wheeled Goods Vehicle', 'Auto Rickshaw', 'Goods Carriage',
       'Chassis Transport', 'Tractor for Agricultural Purpose',
       'Tractor for Commercial Use', 'Ominibus',
       'Trailer For Commercial Use', 'Maxi Cab',
       'Trailer for Agriculture Purpose',
       'Vehicle Fitted with Construction Equipment',
       'Self Loading Concrete Mixer', 'Motor Cycle for Hire',
       'Omnibus for Private Use', 'Loader', 'Fork Lift', 'Ambulance',
       'MOTOR GRADER', 'Tractor Driven Combined Harvester', 'Road Roller',
       'Crane For Private Use', 'SELF PROPELLED HARVESTER',
       'Articulated Vehicles', 'Auto Rikckshaw Private',
       'Mopeds and Motorised Cycle'], dtype=object)

### Since we have fuel '-1', we have to find matching vehicleClass column, we can use it by 2 methods

In [12]:
# Method - 1
# Locating the vehicleClass where the fuel value is -1

df.loc[df['fuel'] == '-1', 'vehicleClass'].value_counts()

vehicleClass
Trailer For Commercial Use         110
Trailer for Agriculture Purpose     85
MOTOR CAR                            2
Name: count, dtype: int64

In [13]:
# Getting the index for the above

df.loc[df['fuel'] == '-1', 'vehicleClass'].value_counts().index

Index(['Trailer For Commercial Use', 'Trailer for Agriculture Purpose',
       'MOTOR CAR'],
      dtype='object', name='vehicleClass')

In [14]:
# Testing the mode of fuel based on the vehicle to fill up the fuel of -1

df.loc[df['vehicleClass'] == 'Trailer For Commercial Use', 'fuel'].mode()[0]

'DIESEL'

In [15]:
# Method - 2

# Grouping the value based on the fuel


fuel_grp = df.groupby(['fuel'])

In [16]:
# getting the vehicleClass based on the fuel "-1"

fuel_index = fuel_grp['vehicleClass'].value_counts().loc['-1'].index

In [17]:
# Here I selected the Method 2 since i want to experience groupby function

def handle_neg_fuel(df):
    fuel_index = fuel_grp['vehicleClass'].value_counts().loc['-1'].index
    for i in fuel_index:
        print(i)
        if(df['fuel']=='-1').any() and (df['vehicleClass'] == i).any():
            print(df.loc[df['vehicleClass'] == i,'fuel'].mode()[0])
            mode_fuel = df.loc[df['vehicleClass'] == i,'fuel'].mode()[0]
            df.loc[df['fuel'] == '-1', 'fuel'] = mode_fuel
        else:
            print('else_part')
handle_neg_fuel(df)

Trailer For Commercial Use
DIESEL
Trailer for Agriculture Purpose
else_part
MOTOR CAR
else_part


In [18]:
# Checking if the -1 value is filled or not!!

df.loc[df['fuel'] == '-1', 'vehicleClass'].value_counts().index

# Since it showed the empty list we conform it changed

Index([], dtype='object', name='vehicleClass')

In [19]:
# Checking the null value for entire dataset

df.isnull().sum()

# Found the null values on columns of
    # 1) fuel
    # 2) colour
    # 3) insuranceValidity

slno                          0
modelDesc                     0
fuel                      12851
colour                      319
vehicleClass                  0
makeYear                      0
seatCapacity                  0
insuranceValidity           135
secondVehicle                 0
tempRegistrationNumber        0
category                      0
makerName                     0
OfficeCd                      0
fromdate                      0
todate                        0
dtype: int64

In [20]:
# I want to check the unique value for columns, to check any custom null value like -- NA, None, Missing

unique_df = df.isnull().sum().index

In [21]:
# checking the unique value with for loop

def check_null(df):
    for i in unique_df:
        print(i)
        print('Column name: ', i,'\n', df[i].value_counts())
        print('\n')
check_null(df)

slno
Column name:  slno 
 slno
6046936     6
2388424     6
4562491     6
5386623     6
2670679     6
           ..
28475       1
28474       1
28473       1
28472       1
12053547    1
Name: count, Length: 354701, dtype: int64


modelDesc
Column name:  modelDesc 
 modelDesc
ACTIVA - 6G DLX BSVI                             20336
ACTIVA- DLX BSVI                                 19462
PULSAR 150 DTS-I BSVI                            16290
ACTIVA-DLX BSVI-PH2                              16231
SHINE-125 DRUM BSVI                              14409
                                                 ...  
MAHINDRA YUVO 415 DI BSIIIA                          1
MAHINDRA BOLERO NEO N10 (O) (R) BSVI                 1
VERNA 1.5 CRDI MT S+ BSVI                            1
LPT4825 10X2 TRK CHASS COWL WO WINSHIELD BSVI        1
NINJA 300 BSVI-PH2                                   1
Name: count, Length: 4365, dtype: int64


fuel
Column name:  fuel 
 fuel
PETROL             477920
DIESEL              7

## We couldn't found any custom null value so we can start to fill the column one by one

## Start with fuel null to fill it out

In [22]:
# As we already gouped fuel we can get mode of vehicleClass as we did already

fuel_grp['vehicleClass'].value_counts()

# Since we haven't updated the groupby object we are still having the "-1", so we cant use it further

fuel             vehicleClass                   
-1               Trailer For Commercial Use           110
                 Trailer for Agriculture Purpose       85
                 MOTOR CAR                              2
BATTERY          MOTOR CYCLE                        28775
                 MOTOR CAR                           5150
                                                    ...  
PETROL ELECTRIC  MOTOR CAR                             73
                 Motor Cab                             14
PETROL LPG       Auto Rickshaw                       3943
                 Auto Rikckshaw Private                 7
                 Three Wheeled Goods Vehicle            1
Name: count, Length: 64, dtype: int64

In [23]:
# So what is the learning here?
# The groupby object is not updated we cant use it further, so we have to use the Method 2
# But it can be useful when we are getting values not suitable for updating it
# else we have to update the groupby object each and everytime

In [24]:
#getting the fuel null velues to match the VehicleClass Column
df['fuel'].isnull()


0         False
1         False
2         False
3         False
4         False
          ...  
627861    False
627862    False
627863    False
627864    False
627865    False
Name: fuel, Length: 627866, dtype: bool

In [25]:
# Matching the fuel null with respective vehicle_Class
df[df['fuel'].isnull()]['vehicleClass'].value_counts().index

Index(['Trailer For Commercial Use', 'Trailer for Agriculture Purpose',
       'Tractor for Commercial Use', 'Tractor for Agricultural Purpose',
       'MOTOR CAR'],
      dtype='object', name='vehicleClass')

In [26]:
# Checking out the results for match with a vehicle with fuel of Null value
df.loc[(df['vehicleClass']=='Trailer For Commercial Use') & (df['fuel'].isnull())].head()

slno                                  modelDesc fuel  \
236  1520606  5 TONS 2 WHEELER SEMI TIPPING T IRON BODY  NaN   
765  3304280  5 TONS 2 WHEELER SEMI TIPPING T IRON BODY  NaN   
912  3307734                         5TONS 2WH TRAILERS  NaN   
923  3812843        5TON 2 WHEELER SEMI TIPPING TRAILER  NaN   
953  4464092      TWO WHEELER TRAILOR TIPPING - 5 TONNS  NaN   

                 colour                vehicleClass    makeYear  seatCapacity  \
236       RED AND BLACK  Trailer For Commercial Use  01/12/2022             0   
765  OREANGE AND YELLOW  Trailer For Commercial Use  01/12/2022             0   
912         BLUE&YELLOW  Trailer For Commercial Use  01/09/2022             0   
923         RED& YELLOW  Trailer For Commercial Use  01/12/2022             0   
953              ORANGE  Trailer For Commercial Use  01/12/2022             0   

    insuranceValidity secondVehicle tempRegistrationNumber   category  \
236        16/12/2023             N            TS21CTR8988  Transport   
765        17/12/2023             N            TS29JTR6375  Transport   
912        01/01/2024             N            TS36DTR8407  Transport   
923        02/01/2024             N           TS04ALTR3319  Transport   
953        26/12/2023             N           TS06ARTR4293  Transport   

                               makerName        OfficeCd    fromdate  \
236   BHAVANI ENGINEERING WORKS JAGITYAL     RTA RAJANNA  01/01/2023   
765            KISAN INDUSTRIES SURYAPET    RTA SURYAPET  01/01/2023   
912          KUMARASWAMY AGRO INDUSTRIES    RTA SIDDIPET  01/01/2023   
923  M/S BHAGYALAKSHMI ENGINEERING WORKS   RTA BHADRADRI  01/01/2023   
953   M/S SRI BADESHWARA ARGO INDUSTRIES  RTA NARAYANPET  01/01/2023   

         todate  
236  02/01/2023  
765  02/01/2023  
912  02/01/2023  
923  02/01/2023  
953  02/01/2023

In [27]:
# Checking the null value in the fuel column
df.loc[(df['fuel'].isnull()),'fuel'].head(5)

236    NaN
765    NaN
912    NaN
923    NaN
953    NaN
Name: fuel, dtype: object

In [28]:
df['fuel'].value_counts().index

Index(['PETROL', 'DIESEL', 'BATTERY', 'CNG PETROL', 'PETROL LPG', 'CNG',
       'PETROL ELECTRIC', 'PETROL CNG', 'LPG'],
      dtype='object', name='fuel')

In [29]:
df.loc[(df['vehicleClass']=='Trailer For Commercial Use') & (df['fuel'].isnull()),'fuel']

236       NaN
765       NaN
912       NaN
923       NaN
953       NaN
         ... 
626755    NaN
627193    NaN
627270    NaN
627462    NaN
627546    NaN
Name: fuel, Length: 7140, dtype: object

In [30]:
def handle_fuel_null(df):
    null_val = df[df['fuel'].isnull()]['vehicleClass'].value_counts().index
    for i in null_val:
        #filt = df['vehicleClass'] == i
        fuel_got = df[df['vehicleClass']==i]['fuel'].mode()[0]
        df.loc[(df['vehicleClass']==i) & (df['fuel'].isnull()),'fuel'] = fuel_got
        print(i,fuel_got)
handle_fuel_null(df)

Trailer For Commercial Use DIESEL
Trailer for Agriculture Purpose DIESEL
Tractor for Commercial Use DIESEL
Tractor for Agricultural Purpose DIESEL
MOTOR CAR PETROL


In [31]:
df.loc[df['slno']==3307734]

slno           modelDesc    fuel       colour  \
912   3307734  5TONS 2WH TRAILERS  DIESEL  BLUE&YELLOW   
4738  3307734  5TONS 2WH TRAILERS  DIESEL  BLUE&YELLOW   

                    vehicleClass    makeYear  seatCapacity insuranceValidity  \
912   Trailer For Commercial Use  01/09/2022             0        01/01/2024   
4738  Trailer For Commercial Use  01/09/2022             0        01/01/2024   

     secondVehicle tempRegistrationNumber   category  \
912              N            TS36DTR8407  Transport   
4738             N            TS36DTR8407  Transport   

                        makerName      OfficeCd    fromdate      todate  
912   KUMARASWAMY AGRO INDUSTRIES  RTA SIDDIPET  01/01/2023  02/01/2023  
4738  KUMARASWAMY AGRO INDUSTRIES  RTA SIDDIPET  02/01/2023  03/01/2023

## Now fill the null value for colour

In [32]:
## Checking out the null values in the Coloru with vehicle class

df.loc[(df['colour'].isnull()),'vehicleClass'].value_counts()

# we found only the Chassis Transport has null value

vehicleClass
Chassis Transport    319
Name: count, dtype: int64

In [33]:
df.loc[(df['colour'].isnull()),'vehicleClass'].value_counts().index


Index(['Chassis Transport'], dtype='object', name='vehicleClass')

In [34]:
# Checkingh the Colours for the chassis tansport

df.loc[(df['vehicleClass']=='Chassis Transport'),'colour'].value_counts()

# We found large number of NIL value
# Because the Chassis vehicle mostly don't have its vehicle body, so we treat them as it is
# And we can assign random colour for the chasis vehicle which can be the better option

colour
NIL                 1525
TITANIUM_WHITE       715
NEW GOLDEN BROWN     237
ARCTIC WHITE         234
TITANIUM WHITE       201
C1ARTCWHIT           152
WHITE                122
M5EDCOATED            83
DAZZLING WHITE        66
BRICK_RED             38
ARCTIC_WHITE          36
BLACK                 34
PRIMER                26
IRISH CREAM           12
C1GLDNBRWN            12
JOSHBLUE              10
LIGHT GREY             7
M5WHITE                7
TITANIM WHITE          6
STABLE GREY            5
ARTIC WHITE            4
TITANIUM_WH            4
RUBY_RED               2
PREMIER                2
YELLOW                 2
NEW GLODEN BROWN       1
TITANIMUM WHITE        1
LIGHT GRAY             1
GOLDEN BROWN           1
Name: count, dtype: int64

In [35]:
# Storing the colour values in a variable
df.loc[(df['vehicleClass']=='Chassis Transport'),'colour'].value_counts().index

Index(['NIL', 'TITANIUM_WHITE', 'NEW GOLDEN BROWN', 'ARCTIC WHITE',
       'TITANIUM WHITE', 'C1ARTCWHIT', 'WHITE', 'M5EDCOATED', 'DAZZLING WHITE',
       'BRICK_RED', 'ARCTIC_WHITE', 'BLACK', 'PRIMER', 'IRISH CREAM',
       'C1GLDNBRWN', 'JOSHBLUE', 'LIGHT GREY', 'M5WHITE', 'TITANIM WHITE',
       'STABLE GREY', 'ARTIC WHITE', 'TITANIUM_WH', 'RUBY_RED', 'PREMIER',
       'YELLOW', 'NEW GLODEN BROWN', 'TITANIMUM WHITE', 'LIGHT GRAY',
       'GOLDEN BROWN'],
      dtype='object', name='colour')

In [36]:
df.loc[df['vehicleClass'] == 'Chassis Transport', 'colour'].dropna().unique()

array(['NIL', 'C1GLDNBRWN', 'TITANIUM WHITE', 'TITANIUM_WHITE',
       'BRICK_RED', 'PRIMER', 'NEW GOLDEN BROWN', 'WHITE', 'ARCTIC WHITE',
       'TITANIM WHITE', 'DAZZLING WHITE', 'IRISH CREAM', 'TITANIUM_WH',
       'ARTIC WHITE', 'ARCTIC_WHITE', 'LIGHT GREY', 'BLACK', 'C1ARTCWHIT',
       'PREMIER', 'YELLOW', 'TITANIMUM WHITE', 'LIGHT GRAY', 'M5WHITE',
       'M5EDCOATED', 'STABLE GREY', 'JOSHBLUE', 'RUBY_RED',
       'NEW GLODEN BROWN', 'GOLDEN BROWN'], dtype=object)

In [37]:
import random
def handle_colour(df):
    null_colour=df.loc[(df['colour'].isnull()),'vehicleClass'].value_counts().index
    avail_colour = df.loc[(df['vehicleClass']=='Chassis Transport'),'colour'].value_counts().index
    for i in null_colour:
        #avail_colour = df.loc[(df['vehicleClass']==i),'colour'].value_counts().index
        print(avail_colour)
        random_colour = random.choice(avail_colour)
        df['colour']=df['colour'].fillna(random_colour)
        print(random_colour)
    else:
        print('else__')
handle_colour(df)

Index(['NIL', 'TITANIUM_WHITE', 'NEW GOLDEN BROWN', 'ARCTIC WHITE',
       'TITANIUM WHITE', 'C1ARTCWHIT', 'WHITE', 'M5EDCOATED', 'DAZZLING WHITE',
       'BRICK_RED', 'ARCTIC_WHITE', 'BLACK', 'PRIMER', 'IRISH CREAM',
       'C1GLDNBRWN', 'JOSHBLUE', 'LIGHT GREY', 'M5WHITE', 'TITANIM WHITE',
       'STABLE GREY', 'ARTIC WHITE', 'TITANIUM_WH', 'RUBY_RED', 'PREMIER',
       'YELLOW', 'NEW GLODEN BROWN', 'TITANIMUM WHITE', 'LIGHT GRAY',
       'GOLDEN BROWN'],
      dtype='object', name='colour')
DAZZLING WHITE
else__


In [38]:
avail_colour = df.loc[(df['vehicleClass']=='Chassis Transport'),'colour'].value_counts().index
avail_colour

Index(['NIL', 'TITANIUM_WHITE', 'DAZZLING WHITE', 'NEW GOLDEN BROWN',
       'ARCTIC WHITE', 'TITANIUM WHITE', 'C1ARTCWHIT', 'WHITE', 'M5EDCOATED',
       'BRICK_RED', 'ARCTIC_WHITE', 'BLACK', 'PRIMER', 'IRISH CREAM',
       'C1GLDNBRWN', 'JOSHBLUE', 'LIGHT GREY', 'M5WHITE', 'TITANIM WHITE',
       'STABLE GREY', 'ARTIC WHITE', 'TITANIUM_WH', 'RUBY_RED', 'PREMIER',
       'YELLOW', 'NEW GLODEN BROWN', 'TITANIMUM WHITE', 'LIGHT GRAY',
       'GOLDEN BROWN'],
      dtype='object', name='colour')

In [39]:
df.loc[(df['colour'].isnull()),'vehicleClass'].value_counts()

Series([], Name: count, dtype: int64)

In [40]:
## We successfully converted the colour null into some colour but the result is not as expected
## I wanted to fill the random colours for the vehicle class, but it filled single colour

In [41]:
df.loc[(df['vehicleClass']=='Chassis Transport'),'colour'].value_counts()

colour
NIL                 1525
TITANIUM_WHITE       715
DAZZLING WHITE       385
NEW GOLDEN BROWN     237
ARCTIC WHITE         234
TITANIUM WHITE       201
C1ARTCWHIT           152
WHITE                122
M5EDCOATED            83
BRICK_RED             38
ARCTIC_WHITE          36
BLACK                 34
PRIMER                26
IRISH CREAM           12
C1GLDNBRWN            12
JOSHBLUE              10
LIGHT GREY             7
M5WHITE                7
TITANIM WHITE          6
STABLE GREY            5
ARTIC WHITE            4
TITANIUM_WH            4
RUBY_RED               2
PREMIER                2
YELLOW                 2
NEW GLODEN BROWN       1
TITANIMUM WHITE        1
LIGHT GRAY             1
GOLDEN BROWN           1
Name: count, dtype: int64

## Now lets fill up for the insurance_validity


In [42]:
df.loc[(df['insuranceValidity'].isnull()),'vehicleClass'].value_counts()

vehicleClass
Chassis Transport                             39
Trailer For Commercial Use                    27
Ambulance                                     26
MOTOR CAR                                     21
Goods Carriage                                13
MOTOR CYCLE                                    4
Vehicle Fitted with Construction Equipment     2
Tractor for Agricultural Purpose               2
Ominibus                                       1
Name: count, dtype: int64

In [43]:
df.loc[(df['vehicleClass']=='Ominibus'),'insuranceValidity'].mode()[0]

'19/03/2024'

In [44]:
df['insuranceValidity'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 627866 entries, 0 to 627865
Series name: insuranceValidity
Non-Null Count   Dtype 
--------------   ----- 
627731 non-null  object
dtypes: object(1)
memory usage: 4.8+ MB


In [45]:
df['insuranceValidity'].isnull().value_counts()

insuranceValidity
False    627731
True        135
Name: count, dtype: int64

In [46]:
df.loc[(df['insuranceValidity'].isnull()) & (df['vehicleClass']=='Ambulance')].head()

slno                                        modelDesc    fuel  \
25027  2736366  FORCE TCRUSERAMBULANCE FM2.6CR30506+PHT4X2 BSVI  DIESEL   
25028  2736367  FORCE TCRUSERAMBULANCE FM2.6CR30506+PHT4X2 BSVI  DIESEL   
25088  2736401  FORCE TCRUSERAMBULANCE FM2.6CR30506+PHT4X2 BSVI  DIESEL   
25089  2736526  FORCE TCRUSERAMBULANCE FM2.6CR30506+PHT4X2 BSVI  DIESEL   
25093  2736505  FORCE TCRUSERAMBULANCE FM2.6CR30506+PHT4X2 BSVI  DIESEL   

           colour vehicleClass    makeYear  seatCapacity insuranceValidity  \
25027  SNOW WHITE    Ambulance  01/11/2022             7               NaN   
25028  SNOW WHITE    Ambulance  01/12/2022             7               NaN   
25088  SNOW WHITE    Ambulance  01/11/2022             7               NaN   
25089  SNOW WHITE    Ambulance  01/12/2022             7               NaN   
25093  SNOW WHITE    Ambulance  01/12/2022             7               NaN   

      secondVehicle tempRegistrationNumber   category             makerName  \
25027             N           TS08CYTR4078  Transport  FORCE MOTORS LIMITED   
25028             N           TS08CYTR4060  Transport  FORCE MOTORS LIMITED   
25088             N           TS08CYTR4044  Transport  FORCE MOTORS LIMITED   
25089             N           TS08CYTR4064  Transport  FORCE MOTORS LIMITED   
25093             N           TS08CYTR4065  Transport  FORCE MOTORS LIMITED   

               OfficeCd    fromdate      todate  
25027    RTA KARIMNAGAR  06/01/2023  07/01/2023  
25028   RTA HANUMAKONDA  06/01/2023  07/01/2023  
25088  RTA-HYDERABAD-CZ  06/01/2023  07/01/2023  
25089       RTA MEDCHAL  06/01/2023  07/01/2023  
25093       RTA KHAMMAM  06/01/2023  07/01/2023

In [47]:
def handle_null_insure(df):
    null_insure = df.loc[(df['insuranceValidity'].isnull()),'vehicleClass'].value_counts().index
    for i in null_insure:
        mode_insure = df.loc[(df['vehicleClass']==i),'insuranceValidity'].mode()[0]
        df.loc[(df['vehicleClass']==i) & (df['insuranceValidity'].isnull()),'insuranceValidity'] = mode_insure
        print(i,mode_insure)

handle_null_insure(df)

Chassis Transport 17/01/2024
Trailer For Commercial Use 15/03/2024
Ambulance 28/09/2023
MOTOR CAR 29/03/2026
Goods Carriage 29/03/2024
MOTOR CYCLE 22/03/2028
Vehicle Fitted with Construction Equipment 02/01/2024
Tractor for Agricultural Purpose 30/05/2024
Ominibus 19/03/2024


In [48]:
df.loc[(df['insuranceValidity']=='28/09/2023') & (df['vehicleClass']=='Ambulance')].head()

slno                                        modelDesc    fuel  \
25027  2736366  FORCE TCRUSERAMBULANCE FM2.6CR30506+PHT4X2 BSVI  DIESEL   
25028  2736367  FORCE TCRUSERAMBULANCE FM2.6CR30506+PHT4X2 BSVI  DIESEL   
25088  2736401  FORCE TCRUSERAMBULANCE FM2.6CR30506+PHT4X2 BSVI  DIESEL   
25089  2736526  FORCE TCRUSERAMBULANCE FM2.6CR30506+PHT4X2 BSVI  DIESEL   
25093  2736505  FORCE TCRUSERAMBULANCE FM2.6CR30506+PHT4X2 BSVI  DIESEL   

           colour vehicleClass    makeYear  seatCapacity insuranceValidity  \
25027  SNOW WHITE    Ambulance  01/11/2022             7        28/09/2023   
25028  SNOW WHITE    Ambulance  01/12/2022             7        28/09/2023   
25088  SNOW WHITE    Ambulance  01/11/2022             7        28/09/2023   
25089  SNOW WHITE    Ambulance  01/12/2022             7        28/09/2023   
25093  SNOW WHITE    Ambulance  01/12/2022             7        28/09/2023   

      secondVehicle tempRegistrationNumber   category             makerName  \
25027             N           TS08CYTR4078  Transport  FORCE MOTORS LIMITED   
25028             N           TS08CYTR4060  Transport  FORCE MOTORS LIMITED   
25088             N           TS08CYTR4044  Transport  FORCE MOTORS LIMITED   
25089             N           TS08CYTR4064  Transport  FORCE MOTORS LIMITED   
25093             N           TS08CYTR4065  Transport  FORCE MOTORS LIMITED   

               OfficeCd    fromdate      todate  
25027    RTA KARIMNAGAR  06/01/2023  07/01/2023  
25028   RTA HANUMAKONDA  06/01/2023  07/01/2023  
25088  RTA-HYDERABAD-CZ  06/01/2023  07/01/2023  
25089       RTA MEDCHAL  06/01/2023  07/01/2023  
25093       RTA KHAMMAM  06/01/2023  07/01/2023

In [49]:
df.isnull().sum()

# By this we have fixed all of our null value, so now onwards we can explore the data

slno                      0
modelDesc                 0
fuel                      0
colour                    0
vehicleClass              0
makeYear                  0
seatCapacity              0
insuranceValidity         0
secondVehicle             0
tempRegistrationNumber    0
category                  0
makerName                 0
OfficeCd                  0
fromdate                  0
todate                    0
dtype: int64

In [50]:
df.shape

(627866, 15)

In [51]:

df.drop_duplicates(inplace=True)

In [52]:
df.shape

(627866, 15)

# Now we can make questions and try to find answers

In [53]:
df.head(2)

slno             modelDesc    fuel                colour vehicleClass  \
0  19139  ACTIVA - 6G DLX BSVI  PETROL  DECENT BLUE METALLIC  MOTOR CYCLE   
1  19210  ACTIVA - 6G DLX BSVI  PETROL  DECENT BLUE METALLIC  MOTOR CYCLE   

     makeYear  seatCapacity insuranceValidity secondVehicle  \
0  01/08/2022             2        01/01/2028             Y   
1  01/09/2022             2        01/01/2028             Y   

  tempRegistrationNumber       category                       makerName  \
0           TS11AGTR3069  Non Transport  HONDA MOTORCYCLE&SCOOTER(I)P L   
1           TS11AGTR3340  Non Transport  HONDA MOTORCYCLE&SCOOTER(I)P L   

      OfficeCd    fromdate      todate  
0  RTA MEDCHAL  01/01/2023  02/01/2023  
1  RTA MEDCHAL  01/01/2023  02/01/2023

In [54]:
# Check out the motorcycle count with fuel wise
motorcycle_fuel = (df['vehicleClass']=='MOTOR CYCLE')
df.loc[(motorcycle_fuel),'fuel'].value_counts()
# Observaation
# Most of the motorcycle are running at Petrol followed by Battery

fuel
PETROL     387039
BATTERY     28775
Name: count, dtype: int64

In [55]:
vehicle_fuel = df['vehicleClass'].value_counts().index
vehicle_fuel

Index(['MOTOR CYCLE', 'MOTOR CAR', 'Auto Rickshaw', 'Goods Carriage',
       'Tractor for Agricultural Purpose', 'Motor Cab',
       'Tractor for Commercial Use', 'Trailer For Commercial Use',
       'Trailer for Agriculture Purpose', 'Three Wheeled Goods Vehicle',
       'Chassis Transport', 'Ominibus', 'Motor Cycle for Hire',
       'Vehicle Fitted with Construction Equipment', 'Omnibus for Private Use',
       'Maxi Cab', 'Tractor Driven Combined Harvester', 'Loader', 'Ambulance',
       'Articulated Vehicles', 'Self Loading Concrete Mixer',
       'SELF PROPELLED HARVESTER', 'Crane For Private Use', 'Road Roller',
       'Fork Lift', 'Auto Rikckshaw Private', 'MOTOR GRADER',
       'Mopeds and Motorised Cycle'],
      dtype='object', name='vehicleClass')

In [56]:
## plotting plots
vehicle_name = []
fuel_name = []
fuel_count = []
for i in vehicle_fuel:
    motorcycle_fuel = (df['vehicleClass']==i)
    fuel = df.loc[(motorcycle_fuel),'fuel'].value_counts()
    vehicle_name.append(i)
    fuel_name.append(fuel.index)
    fuel_count.append(fuel.values)
    
    #print('Vehicle Name : ',i,'\n',fuel,'\n')

In [57]:
fuel_count[0]

array([387039,  28775], dtype=int64)

In [58]:
vehicle_name

['MOTOR CYCLE',
 'MOTOR CAR',
 'Auto Rickshaw',
 'Goods Carriage',
 'Tractor for Agricultural Purpose',
 'Motor Cab',
 'Tractor for Commercial Use',
 'Trailer For Commercial Use',
 'Trailer for Agriculture Purpose',
 'Three Wheeled Goods Vehicle',
 'Chassis Transport',
 'Ominibus',
 'Motor Cycle for Hire',
 'Vehicle Fitted with Construction Equipment',
 'Omnibus for Private Use',
 'Maxi Cab',
 'Tractor Driven Combined Harvester',
 'Loader',
 'Ambulance',
 'Articulated Vehicles',
 'Self Loading Concrete Mixer',
 'SELF PROPELLED HARVESTER',
 'Crane For Private Use',
 'Road Roller',
 'Fork Lift',
 'Auto Rikckshaw Private',
 'MOTOR GRADER',
 'Mopeds and Motorised Cycle']

In [59]:
fuel_name

[Index(['PETROL', 'BATTERY'], dtype='object', name='fuel'),
 Index(['PETROL', 'DIESEL', 'BATTERY', 'CNG PETROL', 'PETROL ELECTRIC', 'CNG'], dtype='object', name='fuel'),
 Index(['CNG PETROL', 'DIESEL', 'PETROL LPG', 'CNG', 'BATTERY', 'PETROL CNG',
        'LPG', 'PETROL'],
       dtype='object', name='fuel'),
 Index(['DIESEL', 'PETROL', 'CNG', 'BATTERY', 'CNG PETROL'], dtype='object', name='fuel'),
 Index(['DIESEL', 'PETROL'], dtype='object', name='fuel'),
 Index(['PETROL', 'CNG PETROL', 'BATTERY', 'DIESEL', 'PETROL ELECTRIC'], dtype='object', name='fuel'),
 Index(['DIESEL'], dtype='object', name='fuel'),
 Index(['DIESEL'], dtype='object', name='fuel'),
 Index(['DIESEL'], dtype='object', name='fuel'),
 Index(['DIESEL', 'BATTERY', 'CNG PETROL', 'CNG', 'PETROL LPG'], dtype='object', name='fuel'),
 Index(['DIESEL', 'CNG'], dtype='object', name='fuel'),
 Index(['DIESEL', 'BATTERY'], dtype='object', name='fuel'),
 Index(['BATTERY', 'PETROL'], dtype='object', name='fuel'),
 Index(['DIESEL'],

In [60]:
fuel_count

[array([387039,  28775], dtype=int64),
 array([83492, 21779,  5150,  3001,    73,     1], dtype=int64),
 array([9604, 5678, 3943, 1737,  413,   51,   13,   12], dtype=int64),
 array([14658,   797,   270,    36,    20], dtype=int64),
 array([14959,     3], dtype=int64),
 array([5983, 2838,  408,  343,   14], dtype=int64),
 array([8184], dtype=int64),
 array([7435], dtype=int64),
 array([5979], dtype=int64),
 array([3862,  956,  103,   76,    1], dtype=int64),
 array([3832,   33], dtype=int64),
 array([2280,   22], dtype=int64),
 array([748, 163], dtype=int64),
 array([788], dtype=int64),
 array([358, 331], dtype=int64),
 array([599,  41], dtype=int64),
 array([206], dtype=int64),
 array([175], dtype=int64),
 array([112,  43], dtype=int64),
 array([146], dtype=int64),
 array([94], dtype=int64),
 array([82], dtype=int64),
 array([45], dtype=int64),
 array([42], dtype=int64),
 array([19], dtype=int64),
 array([7, 5], dtype=int64),
 array([6], dtype=int64),
 array([3], dtype=int64)]

In [61]:
x_index = np.arange(len(fuel_count[1]))

In [62]:
x_index

array([0, 1, 2, 3, 4, 5])

In [63]:
vehicle_name[1]

'MOTOR CAR'

In [64]:
fuel_name[1]

Index(['PETROL', 'DIESEL', 'BATTERY', 'CNG PETROL', 'PETROL ELECTRIC', 'CNG'], dtype='object', name='fuel')

In [ ]:
df.loc[(df['vehicleClass']== 'MOTOR CAR') & (df['fuel']=='DIESEL'),['fuel','vehicleClass','colour']].value_counts()

In [ ]:
df['insuranceValidity'] = pd.to_datetime(df['insuranceValidity'], format='%d/%m/%Y', errors='coerce')